version: '3'

services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'bills-api'
      MONGO_INITDB_ROOT_PASSWORD: 'mamu44'
    ports:
      - '27017:27017'
    networks:
      - local  

  app:
    depends_on:
      - mongo
    container_name: bills
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app
    ports:
      - '3333:3333'
    networks:
      - local

networks:
  local:
    name: local
